### ISSUE TITLE
[Feature] Create m2m relations with existing objects new.m2mfield.set(old.m2mfield.all())

### ISSUE THREAD

**Issue by jackton1** [tj-django/django-clone#703]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

See: https://github.com/tj-django/django-clone/issues/701

### Describe the solution you'd like?

Setting to specify how m2m objects should be cloned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@DanielSchaffer I haven’t and I’ll be happy to review a PR

**Comment by DanielSchaffer** [comment]
Alright, before I get started, this is what I was thinking for the implementation:

- Add a new  `_clone_linked_m2m_fields` attribute
  - Intended to extend the existing naming pattern for configuration attributes in a way that could later be further extend for other relations like m2o
  - Can be defined with `_clone_m2m_fields`, but not `_clone_excluded_m2m_fields`
- Update existing checks related to `_clone_m2m_fields` and `_clone_excluded_m2m_fields` to include `_clone_linked_m2m_fields`
- Add `__duplicate_m2m_linked_fields` method - basically the same as `__duplicate_m2m_fields`, except:
  - Use `_clone_linked_m2m_fields` instead of `_clone_m2m_fields` when building `fields`
  - call `destination.set(list(source.all()))` instead of iterating and cloning `source.all()`
- In `make_clone`, add a call to `__duplicate_m2m_linked_fields`
- Unit tests, of course!

It might make more sense to use `_link` as the prefix for these instead of `_clone`, but I wasn't sure if you'd intended to have `_clone` as a general prefix for the attributes added by the library - I don't have a strong opinion either way.

**Comment by jackton1** [comment]
> It might make more sense to use `_link` as the prefix for these instead of `_clone`, but I wasn't sure if you'd intended to have `_clone` as a general prefix for the attributes added by the library - I don't have a strong opinion either way.

Generally would like to use the prefix `clone` to prevent any confusion with any conflicting installed apps.

**Comment by jackton1** [comment]
Awesome work @DanielSchaffer

**Comment by DanielSchaffer** [comment]
Thank you!
